'use client';
import { useEffect,useState } from 'react';
import { CheckCircle,Loader2 } from 'lucide-react';
export default function SurveyPage({params}:{params:{token:string}}){
 const [survey,setSurvey]=useState<any>(null),[loading,setLoading]=useState(true),[submitting,setSubmitting]=useState(false),[done,setDone]=useState(false),[googleUrl,setGoogleUrl]=useState<string|null>(null);
 const [form,setForm]=useState({rating:0,wentWell:'',improvements:'',wouldRecommend:'',additionalComments:''});
 useEffect(()=>{fetch(`/api/feedback-surveys/${params.token}`).then(r=>r.json()).then(j=>{if(j.survey)setSurvey(j.survey);if(j.survey?.google_review_url)setGoogleUrl(j.survey.google_review_url)}).finally(()=>setLoading(false))},[params.token]);
 async function submit(){if(!form.rating)return;setSubmitting(true);const r=await fetch(`/api/feedback-surveys/${params.token}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(form)});const j=await r.json();if(r.ok){setDone(true);setGoogleUrl(j.googleReviewUrl||googleUrl)}setSubmitting(false)}
 if(loading)return <main className="min-h-screen grid place-items-center bg-slate-50"><Loader2 className="h-7 w-7 animate-spin text-blue-700"/></main>;
 if(done||survey?.completed_at)return <main className="min-h-screen grid place-items-center bg-slate-50 p-4"><section className="max-w-md rounded-2xl border bg-white p-8 text-center shadow-sm"><CheckCircle className="mx-auto mb-4 h-12 w-12 text-emerald-600"/><h1 className="text-2xl font-bold">Takk for tilbakemeldingen</h1><p className="mt-2 text-slate-600">Svaret er mottatt.</p>{googleUrl&&<a href={googleUrl} target="_blank" rel="noreferrer" className="mt-6 inline-block rounded-lg bg-blue-700 px-5 py-3 font-semibold text-white">Del også vurderingen på Google</a>}</section></main>;
 if(!survey)return <main className="min-h-screen grid place-items-center bg-slate-50"><p>Undersøkelsen ble ikke funnet.</p></main>;
 return <main className="min-h-screen bg-slate-50 px-4 py-12"><section className="mx-auto max-w-xl rounded-2xl border bg-white p-7 shadow-sm"><div className="mb-7"><span className="text-sm font-semibold text-blue-700">{survey.company?.name||'Kundetilbakemelding'}</span><h1 className="mt-2 text-3xl font-bold">Hvordan var opplevelsen?</h1><p className="mt-2 text-slate-600">Hei {survey.customer?.name||'der'}. Del en ærlig vurdering av {survey.job?.job_title||'leveransen'}.</p></div>
 <label className="font-semibold">Vurdering fra 1 til 10</label><div className="my-3 flex flex-wrap gap-2">{[1,2,3,4,5,6,7,8,9,10].map(n=><button type="button" key={n} onClick={()=>setForm({...form,rating:n})} className={`h-10 w-10 rounded-lg border font-semibold ${form.rating===n?'border-blue-700 bg-blue-700 text-white':'border-slate-200 bg-white'}`}>{n}</button>)}</div>
 <label className="mt-5 block font-semibold">Hva fungerte bra?</label><textarea rows={3} maxLength={2000} value={form.wentWell} onChange={e=>setForm({...form,wentWell:e.target.value})} className="mt-2 w-full rounded-lg border p-3"/>
 <label className="mt-5 block font-semibold">Hva kan forbedres?</label><textarea rows={3} maxLength={2000} value={form.improvements} onChange={e=>setForm({...form,improvements:e.target.value})} className="mt-2 w-full rounded-lg border p-3"/>
 <button type="button" onClick={submit} disabled={!form.rating||submitting} className="mt-6 w-full rounded-lg bg-blue-700 px-5 py-3 font-semibold text-white disabled:opacity-50">{submitting?'Sender':'Send tilbakemelding'}</button><p className="mt-4 text-xs text-slate-500">Attester publiseres bare etter godkjenning. Lenken til Google vises likt for alle som svarer.</p></section></main>;
}
