// ─── FlowPilot Niche Configuration ────────────────────────────────────────────
// Each niche has: id, name, category, emoji, price, tagline, pain points,
// base features (all get these), niche features, and dashboard module config.

export type NicheFeature = {
  name: string;
  desc: string;
  icon: string;
};

export type Niche = {
  id: string;
  name: string;
  category: string;
  emoji: string;
  priceMonthly: number;
  tagline: string;
  pains: string[];
  baseFeatures: NicheFeature[];    // every niche gets these
  nicheFeatures: NicheFeature[];   // unique to this niche
  modules: string[];               // dashboard sidebar modules to show
  color: string;                   // tailwind color class
  popular?: boolean;
};

// ─── BASE features every single niche gets ─────────────────────────────────
export const BASE_FEATURES: NicheFeature[] = [
  { name: 'AI Chatbot Widget', desc: 'Svar på spørsmål og fang leads automatisk 24/7 fra nettsiden din', icon: '🤖' },
  { name: 'Lead-dashboard', desc: 'Oversikt over alle innkomne henvendelser med score og status', icon: '📊' },
  { name: 'E-postsekvenser', desc: 'Automatisk oppfølging etter innsendt skjema eller booking', icon: '✉️' },
  { name: 'Notater & CRM', desc: 'Logg alle kundedialog, notater og historikk på ett sted', icon: '📝' },
  { name: 'Tilpasset kontaktskjema', desc: 'Legg inn på nettsiden din – leads havner direkte i systemet', icon: '📋' },
  { name: 'Webhook-integrasjon', desc: 'Koble til Zapier, Make eller egne systemer ved nytt lead', icon: '🔗' },
  { name: 'Mobiloptimalisert app', desc: 'Bruk FlowPilot fra mobil – alt fungerer i nettleseren', icon: '📱' },
  { name: 'SEO-verktøy', desc: 'Overvåk din Google-synlighet og get-found-tips per uke', icon: '🔍' },
];

// ─── NICHE DEFINITIONS ──────────────────────────────────────────────────────
export const NICHES: Niche[] = [
  // ── BYGG & HÅNDVERK ──────────────────────────────────────────────────────
  {
    id: 'rorlegger',
    name: 'Rørlegger / VVS',
    category: 'Bygg & Håndverk',
    emoji: '🔧',
    priceMonthly: 2590,
    tagline: 'Fra telefonkø til full kontroll – aldri mist en oppdrag igjen',
    color: 'blue',
    popular: true,
    pains: [
      'Ringer deg på mobil mens du er på jobb – du glemmer å ringe tilbake',
      'Ingen oversikt over hvem som har fått tilbud og hvem som ikke har svart',
      'Fakturering tar timer – skriver det for hånd eller i Excel',
      'Varekostnader spores ikke – vet ikke hva jobber egentlig koster',
    ],
    baseFeatures: BASE_FEATURES,
    nicheFeatures: [
      { name: 'Tilbudsmotor for VVS', desc: 'Lag kalkulerte tilbud med varekostnader, timer og moms inkludert på sekunder', icon: '💰' },
      { name: 'Nødstilfelle-prioritering', desc: 'Marker hasteoppdrag (vannlekkasje) og sorter automatisk til topp', icon: '🚨' },
      { name: 'Leverandørregistret', desc: 'Lagre kontakt og prisliste for Wolseley, Optimera osv – bestill direkte', icon: '🏭' },
      { name: 'Materialkalkulator', desc: 'Beregn rørdiameter, mengde og pris automatisk fra foto eller tegning', icon: '📐' },
      { name: 'Garantiregistrering', desc: 'Logg installasjoner med serienummer og garanti – send påminnelse til kunden', icon: '🛡️' },
      { name: 'Digital jobbjournal', desc: 'Foto + notat per jobb – kunden signerer digitalt på mobil', icon: '📸' },
      { name: 'PDF-faktura (NS3940)', desc: 'Profesjonell faktura med spesifisert materialiste og timepris', icon: '🧾' },
      { name: 'Serviceavtale-CRM', desc: 'Hold oversikt over serviceavtaler, neste service-dato og fornyelse', icon: '🔄' },
    ],
    modules: ['dashboard', 'leads', 'invoices', 'proposals', 'inventory', 'customers', 'tasks', 'forms', 'cashflow', 'settings'],
  },
  {
    id: 'elektriker',
    name: 'Elektriker',
    category: 'Bygg & Håndverk',
    emoji: '⚡',
    priceMonthly: 2590,
    tagline: 'El-bedriften som aldri slipper en ordre – fra første kall til signert smaurtavle',
    color: 'yellow',
    popular: true,
    pains: [
      'Kunder venter i dagevis på tilbud fordi du er opptatt på jobb',
      'FSE-dokumentasjon og samsvarserklæring tar for lang tid',
      'Varekostnader på kabelrull, plugger og automater er vanskelig å spore',
      'Ukjente faktureringsfeil fordi du fakturerer fra hukommelsen',
    ],
    baseFeatures: BASE_FEATURES,
    nicheFeatures: [
      { name: 'Samsvarserklæring-generator', desc: 'Fyll ut NEK 400-krav og generer signert PDF-samsvarserklæring', icon: '📜' },
      { name: 'Anleggsdokumentasjon', desc: 'Last opp tegninger, kursfortegnelse og bilder per oppdrag', icon: '🗂️' },
      { name: 'Kabelmengdekalkulator', desc: 'Beregn metervare, rørvern og mengde fra planløsning', icon: '📐' },
      { name: 'El-journal', desc: 'Digital driftsjornal til DSB-krav med stempel og signatur', icon: '📋' },
      { name: 'Smarthusupsell', desc: 'Registrer om kunden har smarthus-kompatibel tavle og foreslå oppgradering', icon: '🏠' },
      { name: 'Garantilogg', desc: 'Registrer utførte installasjoner med dato og komponentlogg', icon: '🛡️' },
      { name: 'Subkontraktør-oversikt', desc: 'Send arbeidsordre til underleverandører og spor status', icon: '👷' },
      { name: 'Tilbud fra prisbok', desc: 'Legg inn din prisbok – generer tilbud på ett minutt', icon: '💰' },
    ],
    modules: ['dashboard', 'leads', 'invoices', 'proposals', 'inventory', 'customers', 'tasks', 'forms', 'cashflow', 'settings'],
  },
  {
    id: 'snekker',
    name: 'Snekker / Tømrer',
    category: 'Bygg & Håndverk',
    emoji: '🪚',
    priceMonthly: 2590,
    tagline: 'Fra anbud til bygget – prosjektflyt uten papirkaoset',
    color: 'amber',
    pains: [
      'Prosjekter overstiger budsjett fordi materialforbruk ikke spores',
      'For mange parallelle jobber – ingen oversikt over fremdrift',
      'Kunder etterspør fremdriftsrapporter du ikke har tid til å lage',
      'Underleverandører er vanskelig å koordinere',
    ],
    baseFeatures: BASE_FEATURES,
    nicheFeatures: [
      { name: 'Prosjekttidslinje', desc: 'Gantt-lignende visning av alle løpende prosjekter og milepæler', icon: '📅' },
      { name: 'Materiallogg', desc: 'Logg levert treverk, spiker og beslag med kvantum og leverandør', icon: '🪵' },
      { name: 'Kunderapport-generator', desc: 'Ukentlig fremdriftsrapport med bilder sendt automatisk til kunden', icon: '📊' },
      { name: 'Underleverandør-portalen', desc: 'Send arbeidsordre og motta tidregistrering fra fagarbeidere', icon: '👷' },
      { name: 'Klimakalkulator', desc: 'Beregn CO₂-avtrykk per prosjekt (EPC-forberedelse)', icon: '🌱' },
      { name: 'Befaring-booking', desc: 'Kunden booker befaring direkte fra nettsiden din', icon: '📍' },
      { name: 'Garantibevis-PDF', desc: 'Utsted profesjonelt garantibevis til kunden etter ferdig jobb', icon: '🛡️' },
      { name: 'Del-fakturering', desc: 'Fakturèr 30/30/40 eller annen delingsprofil automatisk', icon: '🧾' },
    ],
    modules: ['dashboard', 'leads', 'invoices', 'proposals', 'inventory', 'customers', 'tasks', 'forms', 'cashflow', 'calendar', 'settings'],
  },
  {
    id: 'maler',
    name: 'Maler',
    category: 'Bygg & Håndverk',
    emoji: '🖌️',
    priceMonthly: 2590,
    tagline: 'Fylt opp med oppdrag – kalkylering på to minutter',
    color: 'pink',
    pains: [
      'Kalkylering tar for lang tid – mange avlyser fordi de venter for lenge',
      'Ingen standarisert oppfølging etter befaring',
      'Klage på feil farge eller overflate etter ferdig jobb',
      'Sliter med å skaffe nok oppdrag i vintermånedene',
    ],
    baseFeatures: BASE_FEATURES,
    nicheFeatures: [
      { name: 'Fargevalg-integrasjon', desc: 'Kunden velger farge fra Jotun/Flügger-palette i skjemaet ditt', icon: '🎨' },
      { name: 'Arealskalkulator', desc: 'Beregn maling/mengde automatisk fra oppgitt kvm og antall lag', icon: '📐' },
      { name: 'Befaringsrapport-PDF', desc: 'Dokumenter overflatetilstand med bilder og anbefalinger', icon: '📋' },
      { name: 'Garantioppfølging', desc: 'Send automatisk 1-årsoppfølging for å sjekke overflaten', icon: '🔄' },
      { name: 'Sesong-kampanjer', desc: 'Automatiser vår-/høstkampanje med SMS og e-post til eksisterende kunder', icon: '📣' },
      { name: 'Digital fargeprotokoll', desc: 'Kunden signerer godkjent fargekode digitalt – ingen misforståelser', icon: '✍️' },
      { name: 'Leverandørpris-sporing', desc: 'Hold oversikt over maling- og materialpris fra Biltema, Maxbo osv', icon: '🏭' },
      { name: 'Referansebibliotek', desc: 'Vis ferdigte jobber per kategori på din kundeportale-side', icon: '🖼️' },
    ],
    modules: ['dashboard', 'leads', 'invoices', 'proposals', 'customers', 'forms', 'campaigns', 'cashflow', 'settings'],
  },
  {
    id: 'rengjoring',
    name: 'Rengjøring',
    category: 'Eiendom & Service',
    emoji: '🧹',
    priceMonthly: 2590,
    tagline: 'Gjentakende kunder, automatisert fakturering – voks uten mer jobb',
    color: 'cyan',
    popular: true,
    pains: [
      'Gjentagende fakturaer er tidkrevende å sende manuelt',
      'Kunder avlyser uten varsel – du taper penger',
      'Vanskelig å holde oversikt over hvem som skal ha hva og når',
      'Ansatte vet ikke hva de skal gjøre uten å ringe deg',
    ],
    baseFeatures: BASE_FEATURES,
    nicheFeatures: [
      { name: 'Repeterende avtale-CRM', desc: 'Registrer ukentlig/månedlig vask – fakturaer sendes automatisk', icon: '🔄' },
      { name: 'Sjekkliste-app', desc: 'Ansatte krysser av oppgaver per rom fra mobilen sin', icon: '✅' },
      { name: 'Avbestillingsgebyr', desc: 'Automatisk SMS ved avlysning – gebyret faktureres direkte', icon: '⚠️' },
      { name: 'Nøkkelhåndtering', desc: 'Logg hvem som har nøkkel til hvilken adresse og siden når', icon: '🔑' },
      { name: 'Rengjøringsstatus-portal', desc: 'Kunden ser i sanntid om jobben er startet/ferdig', icon: '📍' },
      { name: 'Ansatt-timeregistrering', desc: 'Registrer timer per adresse – kobles til faktura automatisk', icon: '⏱️' },
      { name: 'Kundekort med spesielle ønsker', desc: 'Notér allergier, ikke-soner og spesialvask per kunde', icon: '📌' },
      { name: 'Google-anmeldelse-forespørsel', desc: 'Send automatisk review-forespørsel etter ferdig vask', icon: '⭐' },
    ],
    modules: ['dashboard', 'leads', 'invoices', 'customers', 'tasks', 'calendar', 'forms', 'cashflow', 'workflows', 'settings'],
  },
  {
    id: 'frisor',
    name: 'Frisør / Salong',
    category: 'Helse & Velvære',
    emoji: '✂️',
    priceMonthly: 2590,
    tagline: 'Fullbooket kalender, automatisk kassesystem og produktsalg i ett',
    color: 'rose',
    popular: true,
    pains: [
      'Taper penger på no-shows som ikke avlyser',
      'Manuell kassaregistrering etter hvert salg tar tid',
      'Ingen kontroll på hvilke produkter som er igjen på hylla',
      'Kunder glemmer time og viser ikke opp',
    ],
    baseFeatures: BASE_FEATURES,
    nicheFeatures: [
      { name: 'Online booking-system', desc: 'Kunder booker time direkte fra Instagram, Google og nettsiden', icon: '📅' },
      { name: 'Produktkasse + lager', desc: 'Skann produkt ved salg → varelager oppdateres automatisk', icon: '🛒' },
      { name: 'No-show betaling', desc: 'Kunder legger kortdata ved booking – gebyr trekkes ved uteblivelse', icon: '💳' },
      { name: 'Lojalitetsprogram', desc: 'Poeng for hvert besøk – automatisk rabattkode ved 10 besøk', icon: '🎁' },
      { name: 'SMS-påminnelse', desc: '24 timer og 2 timer før time – kunden bekrefter med ett svar', icon: '📲' },
      { name: 'Produktbestilling til leverandør', desc: 'Lavt lager? Trykk "bestill" – e-post sendes direkte til leverandør', icon: '📦' },
      { name: 'Stilhistorikk per kunde', desc: 'Notér farge, teknikk og produkt per besøk – husk alt', icon: '💇' },
      { name: 'Gavekort-system', desc: 'Selg og løs inn digitale gavekort uten tredjepartsapp', icon: '🎀' },
    ],
    modules: ['dashboard', 'leads', 'calendar', 'customers', 'inventory', 'invoices', 'forms', 'review-gatekeeper', 'campaigns', 'cashflow', 'settings'],
  },
  {
    id: 'hudpleie',
    name: 'Hudpleie / Negle / Spa',
    category: 'Helse & Velvære',
    emoji: '💅',
    priceMonthly: 2590,
    tagline: 'Butikk, booking og kundepleie – alt i én app',
    color: 'purple',
    pains: [
      'Kunder bestiller via Instagram DM – ingenting er strukturert',
      'Ingen oversikt over hvilke behandlinger kunden har hatt',
      'Produktene tar slutt midt i sesongen',
      'Vanskelig å ta seg betalt for no-shows',
    ],
    baseFeatures: BASE_FEATURES,
    nicheFeatures: [
      { name: 'Behandlingshistorikk', desc: 'Logg behandlingstype, produkter og reaksjoner per kunde', icon: '📋' },
      { name: 'Kontraindikasjon-skjema', desc: 'Kunden fyller ut helseskjema digitalt – signert og lagret', icon: '⚕️' },
      { name: 'Produktkasse + varsel ved lavt lager', desc: 'Selg CND, Essie osv og få varsel når det nærmer seg tomt', icon: '🛒' },
      { name: 'Pakkesolgt tidenes', desc: 'Selg 5-for-4, gavepakker og sesongpakker med rabatt i appen', icon: '🎁' },
      { name: 'Kundekort med allergier', desc: 'Registrer allergi og sensitiv hud – advarsel vises ved neste booking', icon: '⚠️' },
      { name: 'Bilder per behandling', desc: 'Ta og lagre "før og etter"-bilder knyttet til kundens profil', icon: '📸' },
      { name: 'Online booking med påminnelse', desc: 'Booking fra Instagram, Google og nettside med SMS-varsel', icon: '📅' },
      { name: 'Gavekort og kampanjer', desc: 'Digitale gavekort + sesongkampanjer sendes automatisk', icon: '🎀' },
    ],
    modules: ['dashboard', 'leads', 'calendar', 'customers', 'inventory', 'invoices', 'forms', 'campaigns', 'cashflow', 'settings'],
  },
  {
    id: 'personlig-trener',
    name: 'PT / Treningssenter',
    category: 'Helse & Velvære',
    emoji: '🏋️',
    priceMonthly: 2590,
    tagline: 'Fyll opp klasser og følg opp klienter – automatisk',
    color: 'green',
    pains: [
      'Klienter dropper ut uten at du fanger det opp i tide',
      'Klasse-påmelding skjer på SMS og Messenger – kaotisk',
      'Fakturering av månedlig abonnement er manuelt arbeid',
      'Ingen oversikt over fremdrift per klient',
    ],
    baseFeatures: BASE_FEATURES,
    nicheFeatures: [
      { name: 'Klasse-booking', desc: 'Online påmelding til klasser med kapasitetsbegrensning', icon: '📅' },
      { name: 'Treningsprogram-CRM', desc: 'Logg program, sett, reps og vekt per klient per økt', icon: '🏃' },
      { name: 'Abonnementsadministrasjon', desc: 'Månedlig betaling trekkes automatisk – ingen purringer', icon: '💳' },
      { name: 'Fremgangsmåling', desc: 'Klienten logg vekt og mål selv – du ser grafen i dashboardet', icon: '📈' },
      { name: 'Droppout-varsel', desc: 'Få varsling hvis en klient ikke har vært innom på 2 uker', icon: '⚠️' },
      { name: 'Kostholdsnotat', desc: 'Logg kostholdsplan og matvaner knyttet til klientens profil', icon: '🥗' },
      { name: 'Prøvetime-konvertering', desc: 'Automatisk oppfølging til prøvetimeklienter etter 48 timer', icon: '✉️' },
      { name: 'Venteliste-håndtering', desc: 'Full klasse? Kunden meldes automatisk-på ved avmelding', icon: '⏳' },
    ],
    modules: ['dashboard', 'leads', 'calendar', 'customers', 'invoices', 'forms', 'workflows', 'cashflow', 'settings'],
  },
  {
    id: 'regnskapsforer',
    name: 'Regnskapsfører',
    category: 'Tjenesteyting & Konsulent',
    emoji: '📒',
    priceMonthly: 3990,
    tagline: 'Fra første klientkontakt til signert oppdragsavtale – automatisert',
    color: 'teal',
    pains: [
      'For mye tid på å sende purringer og påminnelser til klienter',
      'Onboarding av nye klienter er manuelt og tidkrevende',
      'Vanskelig å håndtere frister (MVA, A-melding, skattemelding) for mange klienter',
      'Priser og tjenester kommuniseres inkonsekvent',
    ],
    baseFeatures: BASE_FEATURES,
    nicheFeatures: [
      { name: 'Fristhåndterer', desc: 'Oversikt over MVA-frister, A-melding og selvangivelse per klient automatisk', icon: '📅' },
      { name: 'Oppdragsavtale-generator', desc: 'Generer og send signert oppdragsavtale til ny klient på sekunder', icon: '📜' },
      { name: 'Dokumentmottak', desc: 'Klient laster opp bilag via klientportalen – du ser dem direkte', icon: '📂' },
      { name: 'Månedlig timekostnad', desc: 'Logg timer per klient og generer faktura med spesifisert tidsliste', icon: '⏱️' },
      { name: 'Klient-onboarding', desc: 'Automatisk velkomstsekvens med sjekkliste for nye klienter', icon: '👋' },
      { name: 'Purring-automasjon', desc: 'Manglende bilag? System sender automatisk purring til klient', icon: '🔔' },
      { name: 'Klientportal', desc: 'Kunden ser egne dokumenter, fakturaer og frister i sin portal', icon: '🌐' },
      { name: 'Rapportering til styre', desc: 'Generer månedlig driftsrapport PDF til styret med 2 klikk', icon: '📊' },
    ],
    modules: ['dashboard', 'leads', 'invoices', 'customers', 'tasks', 'forms', 'cashflow', 'workflows', 'client-portal', 'settings'],
  },
  {
    id: 'it-konsulent',
    name: 'IT-konsulent',
    category: 'Tjenesteyting & Konsulent',
    emoji: '💻',
    priceMonthly: 3990,
    tagline: 'Fra lead til leveranse – prosjektstyring og fakturering i ett',
    color: 'indigo',
    pains: [
      'Scope creep er vanskelig å fakturere fordi det ikke er dokumentert',
      'Klienter ringer utenom arbeidstid – ingen support-struktur',
      'Vanskelig å vise verdien av arbeidet til ikke-tekniske kunder',
      'Månedlige support-fakturaer sendes for sent',
    ],
    baseFeatures: BASE_FEATURES,
    nicheFeatures: [
      { name: 'Support-ticket-system', desc: 'Klient sender henvendelse via portal – du prioriterer og løser', icon: '🎫' },
      { name: 'SLA-overvåkning', desc: 'Sett responstidsmål og få varsel hvis du er i ferd med å bryte SLA', icon: '⏱️' },
      { name: 'Prosjektscope-dokumentasjon', desc: 'Kunden signerer scope digitalt – scope creep faktureres rettferdig', icon: '📜' },
      { name: 'Teknisk rapport-generator', desc: 'Generer lesbar IT-rapport til ikke-teknisk ledelse', icon: '📊' },
      { name: 'MRR-tracker', desc: 'Oversikt over recurring support-inntekter per klient per måned', icon: '💹' },
      { name: 'Lisens-logg', desc: 'Registrer alle softwarelisenser per klient med utløpsdato', icon: '🔑' },
      { name: 'Change-request-flyt', desc: 'Endringsforespørsler godkjennes og faktureres digitalt', icon: '🔄' },
      { name: 'Onboarding-automatisering', desc: 'Ny klient? Automatisk oppsettssjekkliste og velkomst-e-post', icon: '🚀' },
    ],
    modules: ['dashboard', 'leads', 'invoices', 'customers', 'tasks', 'pipeline', 'forms', 'cashflow', 'workflows', 'client-portal', 'settings'],
  },
  {
    id: 'eiendomsmegler',
    name: 'Eiendomsmegler',
    category: 'Eiendom & Bolig',
    emoji: '🏠',
    priceMonthly: 3990,
    tagline: 'Verdiestimater, salgspipen og kjøperprofiler – alt i ett CRM',
    color: 'slate',
    popular: true,
    pains: [
      'Potensielle selgere glemmes bort etter første kontakt',
      'Ingen oversikt over hvilke kjøpere som passer til hvilke objekter',
      'E-takstkommunikasjon er ustrukturert',
      'Oppfølging av kjøperlisten etter salg er manuelt',
    ],
    baseFeatures: BASE_FEATURES,
    nicheFeatures: [
      { name: 'Salgspipeline-visualisering', desc: 'Se alle objekter fra "vurdering" til "solgt" i én oversikt', icon: '🏘️' },
      { name: 'Kjøperprofil-CRM', desc: 'Registrer søkeprofil, budsjett og ønsker per kjøper', icon: '👥' },
      { name: 'Automatisk matching', desc: 'Nytt objekt? AI matcher og varsler relevante kjøpere automatisk', icon: '🔔' },
      { name: 'Visning-håndtering', desc: 'Interessenter booker visning fra annonsen – du ser listen direkte', icon: '📅' },
      { name: 'Budgjennomgang', desc: 'Logg alle bud med tidspunkt og budrunde-historikk per objekt', icon: '💰' },
      { name: 'Selger-rapport', desc: 'Ukentlig automatisk rapport til selger om aktivitet og visninger', icon: '📊' },
      { name: 'Kontraktshåndtering', desc: 'Last opp og arkiver kjøpers- og selgerskontrakter per objekt', icon: '📜' },
      { name: 'Ettersalg-CRM', desc: 'Følg opp solgte kunder med innflyttingshjelp og referanseforespørsel', icon: '🤝' },
    ],
    modules: ['dashboard', 'leads', 'pipeline', 'customers', 'calendar', 'tasks', 'forms', 'cashflow', 'workflows', 'settings'],
  },
  {
    id: 'vaktmester',
    name: 'Vaktmester / Eiendomsdrift',
    category: 'Eiendom & Bolig',
    emoji: '🏢',
    priceMonthly: 2590,
    tagline: 'Hold oversikt over alle eiendommer, jobber og kontrakter',
    color: 'stone',
    pains: [
      'For mange eiendommer og oppgaver å huske – ingenting er loggført',
      'Fakturering av faste oppdrag glemmes iblant',
      'Varsling om feil og mangler fra leietakere er kaotisk',
      'Servicehistorikk per eiendom finnes ikke',
    ],
    baseFeatures: BASE_FEATURES,
    nicheFeatures: [
      { name: 'Eiendomsregister', desc: 'Registrer alle eiendommer med kontakt, utstyr og historikk', icon: '🏗️' },
      { name: 'Feilmeldings-portal', desc: 'Leietaker melder feil via QR-kode – du ser og prioriterer', icon: '🔔' },
      { name: 'Serviceintervall-kalender', desc: 'Automatisk varsling når ventilasjonsfilter, brannvern eller heis er forfalt', icon: '📅' },
      { name: 'Kontraktsforvaltning', desc: 'Håndter forvaltningskontrakter med automatisk fornyelsespåminnelse', icon: '📜' },
      { name: 'Underleverandørkoordinering', desc: 'Send arbeidsordre til rørlegger, elektriker eller maler direkte', icon: '👷' },
      { name: 'Digital rundsjekk', desc: 'Gjennomfør HMS-runde med sjekkliste og foto fra mobil', icon: '📱' },
      { name: 'Kostnadsrapport per eiendom', desc: 'Se drifts- og vedlikeholdskostnader per adresse over tid', icon: '💰' },
      { name: 'Leietakerhistorikk', desc: 'Logg alle kommunikasjonspunkter med leietaker per adresse', icon: '📋' },
    ],
    modules: ['dashboard', 'leads', 'customers', 'tasks', 'calendar', 'invoices', 'forms', 'cashflow', 'settings'],
  },
  {
    id: 'restaurant',
    name: 'Restaurant / Kafé',
    category: 'Mat & Drikke',
    emoji: '🍽️',
    priceMonthly: 2590,
    tagline: 'Bordbooking, ansattkommunikasjon og kampanjer – alt på ett sted',
    color: 'orange',
    pains: [
      'Bordbooking per telefon er kaotisk i rushtid',
      'Ansatte vet ikke menyendringer eller kampanjer i tide',
      'Ingen systematisk innhenting av gjesteanmeldelser',
      'Svinn og varekostnader spores ikke',
    ],
    baseFeatures: BASE_FEATURES,
    nicheFeatures: [
      { name: 'Bordbooking-system', desc: 'Gjester booker bord online – du ser kapasitetsoversikt i sanntid', icon: '🪑' },
      { name: 'Menyanmeldelse-innhenting', desc: 'Send automatisk Tripadvisor/Google-forespørsel etter besøk', icon: '⭐' },
      { name: 'Vare-svinnlogg', desc: 'Logg svinn per ingrediens – kobles til ukentlig kostrapport', icon: '📊' },
      { name: 'Kampanje-SMS', desc: 'Send tilbud til alle gjester som har spist der siste 3 måneder', icon: '📲' },
      { name: 'Digital meny-QR', desc: 'Oppdater menyen digitalt – gjestene skanner QR ved bordet', icon: '📋' },
      { name: 'Event-booking', desc: 'Selger bursdag- og bedriftsarrangementer via nettskjema', icon: '🎉' },
      { name: 'Gavekort-system', desc: 'Selg og aktiver digitale gavekort uten ekstra app', icon: '🎁' },
      { name: 'Ansatt-informasjon', desc: 'Send daglig brief til alle ansatte med dagens meny og spesial', icon: '👨‍🍳' },
    ],
    modules: ['dashboard', 'leads', 'calendar', 'customers', 'inventory', 'campaigns', 'forms', 'cashflow', 'review-gatekeeper', 'settings'],
  },
  {
    id: 'transport',
    name: 'Transport / Budservice',
    category: 'Transport & Logistikk',
    emoji: '🚚',
    priceMonthly: 2590,
    tagline: 'Ordrer, ruter og fakturering – uten Excel',
    color: 'sky',
    pains: [
      'Kunder ringer på feil tidspunkt og forstyrrer sjåfør',
      'Ruteoptimalisering gjøres manuelt og tar tid',
      'Fakturering av faktiske kjørte km er upresist',
      'Ingen oversikt over kjøretøyets service-historikk',
    ],
    baseFeatures: BASE_FEATURES,
    nicheFeatures: [
      { name: 'Ordre-app for sjåfør', desc: 'Sjåfør mottar oppdrag på mobil med kart og instruksjoner', icon: '📱' },
      { name: 'Kjøretøyregister', desc: 'Logg alle kjøretøy med km-stand, service-intervall og forsikring', icon: '🚗' },
      { name: 'Kilometer-fakturering', desc: 'GPS-logg kobles til faktura – presist på meteren', icon: '🗺️' },
      { name: 'Returlast-koordinering', desc: 'Registrer ledige lasterom på returnsturer – selg kapasiteten', icon: '↩️' },
      { name: 'Kundeportal for sporing', desc: 'Kunden sporer forsendelsen live via lenke du sender', icon: '📍' },
      { name: 'Servicedato-kalender', desc: 'Automatisk varsel 2 uker før EU-kontroll eller service forfaller', icon: '🔧' },
      { name: 'Frakt-tilbuds-generator', desc: 'Beregn fraktkostnad basert på avstand, vekt og kjøretøy', icon: '💰' },
      { name: 'Sjåfør-timelogg', desc: 'Sjåfør registrerer tidspunkter – kobles til lønnsgrunnlag', icon: '⏱️' },
    ],
    modules: ['dashboard', 'leads', 'invoices', 'customers', 'tasks', 'calendar', 'forms', 'cashflow', 'settings'],
  },
  {
    id: 'bilverksted',
    name: 'Bilverksted',
    category: 'Bil & Kjøretøy',
    emoji: '🔩',
    priceMonthly: 2590,
    tagline: 'Jobbkort, lager og faktura – fra kunden leverer til de henter',
    color: 'zinc',
    pains: [
      'Jobbkort skrives for hånd og forsvinner',
      'Deler bestilles ad hoc uten oversikt over lagerstatus',
      'Kunder vet ikke når bilen er ferdig',
      'Fakturering tar lang tid fordi delene ikke er logget',
    ],
    baseFeatures: BASE_FEATURES,
    nicheFeatures: [
      { name: 'Digitalt jobbkort', desc: 'Registrer problem, deler og timer per bil – faktura genereres automatisk', icon: '📋' },
      { name: 'Reservedelslager', desc: 'Søk, reserver og bestill deler direkte i systemet', icon: '🔧' },
      { name: 'Klar-SMS til kunde', desc: 'Automatisk melding: "Din bil er klar for henting kl 15:30"', icon: '📲' },
      { name: 'EU-kontroll-CRM', desc: 'Logg neste EU-kontroll per bil – send SMS 2 uker i forveien', icon: '📅' },
      { name: 'Verkstedkalender', desc: 'Vis kapasitet per mekaniker og tid per jobbtype', icon: '📆' },
      { name: 'Forsikringsoppgjør-dokumentasjon', desc: 'Logg skadebilder og kostnader – eksporter til forsikringsselskap', icon: '📸' },
      { name: 'Stamkundeprogram', desc: 'Logg besøk og tilby rabatt etter 5 service-besøk', icon: '🎁' },
      { name: 'Dekkshotell', desc: 'Registrer hvilke dekk som tilhører hvilken kunde og lagringsplass', icon: '🏷️' },
    ],
    modules: ['dashboard', 'leads', 'invoices', 'customers', 'inventory', 'calendar', 'tasks', 'forms', 'cashflow', 'settings'],
  },
  {
    id: 'markedsbyra',
    name: 'Markedsføringsbyrå',
    category: 'Tjenesteyting & Konsulent',
    emoji: '📣',
    priceMonthly: 3990,
    tagline: 'Fra lead-gen til rapport – byråflyt uten kaoset',
    color: 'fuchsia',
    pains: [
      'Klienter forventer jevnlige rapporter du ikke rekker å lage',
      'Arbeidsordrer og kreativt arbeid er vanskelig å prise',
      'Sporadisk fakturering gir ujevn kontantstrøm',
      'Prosjekter leveres sent fordi oppgavestyring mangler',
    ],
    baseFeatures: BASE_FEATURES,
    nicheFeatures: [
      { name: 'Kampanjeplanlegger', desc: 'Planlegg alle klientkampanjer i én kalender med deadlines', icon: '📅' },
      { name: 'Resultatrapport-generator', desc: 'Hent data fra Google Ads og Meta – lag rapport i én klikk', icon: '📊' },
      { name: 'Kreativ brief-mal', desc: 'Klient fyller ut brief digitalt – brief havner direkte i prosjektet', icon: '📝' },
      { name: 'Retainer-fakturering', desc: 'Fast månedlig faktura sendes automatisk per klient', icon: '💳' },
      { name: 'Godkjenningsflyt', desc: 'Klient godkjenner annonsekreativ digitalt med kommentarfunksjon', icon: '✅' },
      { name: 'Tidregistrering per klient', desc: 'Logg timer per oppgave – vis klienten hva pengene gikk til', icon: '⏱️' },
      { name: 'Budsjettsporing', desc: 'Se forbruk vs. budsjett per kanal og klient i sanntid', icon: '💰' },
      { name: 'Lead-rapport til klient', desc: 'Automatisk ukentlig oppsummering av leads pr. kanal til klienten', icon: '📬' },
    ],
    modules: ['dashboard', 'leads', 'invoices', 'customers', 'pipeline', 'campaigns', 'social-planner', 'tasks', 'forms', 'cashflow', 'workflows', 'analytics', 'settings'],
  },
  {
    id: 'tannlege',
    name: 'Tannlege / Tannpleier',
    category: 'Helse & Velvære',
    emoji: '🦷',
    priceMonthly: 3990,
    tagline: 'Fullbooket timebok og automatisk pasientkommunikasjon',
    color: 'sky',
    pains: [
      'Pasienter avlyser timen uten varsel – kostbar tapt tid',
      'Manuell purring på tilbakevendende kontroll tar tid',
      'Nye pasienter registreres på papirskjema',
      'Ingen oversikt over kommende timer og ledig kapasitet',
    ],
    baseFeatures: BASE_FEATURES,
    nicheFeatures: [
      { name: 'Timebooking for pasienter', desc: 'Pasienten booker time online – du ser full timebok i dashboardet', icon: '📅' },
      { name: 'Innkallingssystem', desc: 'Automatisk SMS/e-post hvert halvår: "Din time er forfalt – book nå"', icon: '📲' },
      { name: 'Pasient-journalnotat', desc: 'Logg behandlingsoversikt per pasient med dato og behandler', icon: '📋' },
      { name: 'Digital pasientregistrering', desc: 'Nytt pasient fyller inn info digitalt fra lenke – du slipper papir', icon: '📱' },
      { name: 'No-show-gebyr', desc: 'Kunden lagrer kort ved booking – gebyr ved avlysning < 24t', icon: '💳' },
      { name: 'Risikogruppe-flagging', desc: 'Merk pasienter som krever ekstra tid eller utstyr', icon: '🚩' },
      { name: 'Behandlingsplan-PDF', desc: 'Send personlig behandlingsplan til pasient etter konsultasjon', icon: '📜' },
      { name: 'Anmeldelsesforspørsel', desc: 'Automatisk Google-anmeldelseforespørsel etter ferdig behandling', icon: '⭐' },
    ],
    modules: ['dashboard', 'leads', 'calendar', 'customers', 'forms', 'review-gatekeeper', 'campaigns', 'cashflow', 'settings'],
  },
  {
    id: 'advokat',
    name: 'Advokat / Juridisk rådgivning',
    category: 'Tjenesteyting & Konsulent',
    emoji: '⚖️',
    priceMonthly: 3990,
    tagline: 'Klienthåndtering, frister og timefakturering under kontroll',
    color: 'slate',
    pains: [
      'Frister glemmes fordi de er spredt over mange systemer',
      'Timefakturering er unøyaktig og leveres for sent',
      'Klienter forventer sanntidsstatus på sin sak',
      'Sensitiv dokumenthåndtering er ustrukturert',
    ],
    baseFeatures: BASE_FEATURES,
    nicheFeatures: [
      { name: 'Sakspipeline', desc: 'Logg alle saker fra inntak til avsluttet med status og neste steg', icon: '⚖️' },
      { name: 'Fristkalender', desc: 'Rettsdatoer, frister og avtaledatoer med automatisk påminnelse', icon: '📅' },
      { name: 'Timeregistrering', desc: 'Logg timer per sak – generer faktura med spesifisert tidsliste', icon: '⏱️' },
      { name: 'Klientportal', desc: 'Klient ser saksstatus og kan laste opp dokumenter sikkert', icon: '🌐' },
      { name: 'Oppdragsavtale-generator', desc: 'Digital signert oppdragsavtale sendes og mottas i appen', icon: '📜' },
      { name: 'Dokumentarkiv per sak', desc: 'All korrespondanse og dokumenter er arkivert og søkbart', icon: '🗂️' },
      { name: 'Konfliktkontroll', desc: 'Søk eksisterende klienter for å avdekke interessekonflikter', icon: '🔍' },
      { name: 'Fakturastatus-oversikt', desc: 'Se alle ubetalte timer og forventede inntekter per klient', icon: '💰' },
    ],
    modules: ['dashboard', 'leads', 'invoices', 'customers', 'pipeline', 'tasks', 'calendar', 'forms', 'cashflow', 'client-portal', 'settings'],
  },
  {
    id: 'landbruk',
    name: 'Gartner / Landbrukstjenester',
    category: 'Landbruk & Utemiljø',
    emoji: '🌱',
    priceMonthly: 2590,
    tagline: 'Sesongstyring og kundeoppfølgng – uansett vær',
    color: 'lime',
    pains: [
      'Alt arbeid er sesongstyrt – ingenting planlegges i sanntid',
      'Faste kunder for klipping og snømåking glemmes mellom sesonger',
      'Materialkostnader for planter og jord spores ikke',
      'Ingen oversikt over planlagte hager og hva som gjelder',
    ],
    baseFeatures: BASE_FEATURES,
    nicheFeatures: [
      { name: 'Sesong-CRM', desc: 'Kontakter reaktiveres automatisk ved neste sesong med tilbudsutsendelse', icon: '🌿' },
      { name: 'Hageprofil per kunde', desc: 'Logg hagetype, planter og ønsker per adresse', icon: '🏡' },
      { name: 'Serviceavtale-system', desc: 'Klippeavtaler med automatisk fakturering per sesong', icon: '🔄' },
      { name: 'Materiallogg', desc: 'Spor forbruk av planter, jord og steinmaterialer per oppdrag', icon: '🌳' },
      { name: 'Vær-integrasjon varsel', desc: 'Få varsel om frost eller nedbør som påvirker planlagte jobber', icon: '🌤️' },
      { name: 'Snøryddingsskjema', desc: 'Aktiver snøryddingskunder automatisk ved første snøvarsel', icon: '❄️' },
      { name: 'Prosjektfoto-galleri', desc: 'Dokumenter ferdigte hager med bilder tilknyttet kundens profil', icon: '📸' },
      { name: 'Leverandørordre', desc: 'Bestill planter og materialer direkte fra leverandørens prisliste', icon: '📦' },
    ],
    modules: ['dashboard', 'leads', 'invoices', 'customers', 'calendar', 'inventory', 'forms', 'cashflow', 'settings'],
  },
];

// ─── Quiz: onboarding questions to determine niche ─────────────────────────
export type QuizOption = { value: string; label: string; emoji: string };
export type QuizQuestion = { id: string; question: string; options: QuizOption[] };

export const QUIZ_QUESTIONS: QuizQuestion[] = [
  {
    id: 'industry',
    question: 'Hva driver du med?',
    options: [
      { value: 'bygg', label: 'Bygg, håndverk eller montering', emoji: '🏗️' },
      { value: 'helse', label: 'Helse, velvære eller salong', emoji: '💆' },
      { value: 'tjenester', label: 'Konsulent, IT eller rådgivning', emoji: '💼' },
      { value: 'eiendom', label: 'Eiendom eller drift/renhold', emoji: '🏠' },
      { value: 'mat', label: 'Restaurant, kafé eller mat', emoji: '🍽️' },
      { value: 'transport', label: 'Transport, logistikk eller kjøretøy', emoji: '🚚' },
      { value: 'handel', label: 'Handel, nettbutikk eller import', emoji: '🛒' },
      { value: 'annet', label: 'Noe annet', emoji: '✨' },
    ],
  },
  {
    id: 'customers',
    question: 'Hvem selger du til?',
    options: [
      { value: 'b2c', label: 'Privatpersoner (B2C)', emoji: '👤' },
      { value: 'b2b', label: 'Andre bedrifter (B2B)', emoji: '🏢' },
      { value: 'both', label: 'Begge deler', emoji: '🤝' },
    ],
  },
  {
    id: 'pain',
    question: 'Hva er ditt største problem i dag?',
    options: [
      { value: 'leads', label: 'Mister henvendelser og oppdrag', emoji: '📉' },
      { value: 'admin', label: 'For mye tid på admin og fakturering', emoji: '📋' },
      { value: 'followup', label: 'Dårlig oppfølging av kunder', emoji: '📱' },
      { value: 'growth', label: 'Sliter med å vokse og skaffe nye kunder', emoji: '🚀' },
    ],
  },
  {
    id: 'size',
    question: 'Hvor mange ansatte har dere?',
    options: [
      { value: 'solo', label: 'Bare meg', emoji: '🧑' },
      { value: 'small', label: '2–5', emoji: '👥' },
      { value: 'medium', label: '6–20', emoji: '🏢' },
      { value: 'large', label: '20+', emoji: '🏭' },
    ],
  },
];

// ─── Scoring: map quiz answers to niche IDs ─────────────────────────────────
export function matchNiche(answers: Record<string, string>): string {
  const { industry } = answers;
  const mappings: Record<string, string> = {
    'bygg': 'rorlegger',
    'helse': 'frisor',
    'tjenester': 'it-konsulent',
    'eiendom': 'rengjoring',
    'mat': 'restaurant',
    'transport': 'transport',
    'handel': 'bilverksted',
    'annet': 'regnskapsforer',
  };
  return mappings[industry] ?? 'rorlegger';
}

export function getNiche(id: string): Niche | undefined {
  return NICHES.find(n => n.id === id);
}

export const NICHE_CATEGORIES = [...new Set(NICHES.map(n => n.category))];
