'use client';
import { useEffect,useMemo,useState } from 'react';
import { CheckCircle,Clock,Loader2 } from 'lucide-react';
type Survey={id:string;survey_token:string;sent_at?:string;completed_at?:string;question_1_rating?:number;question_2_text?:string;question_3_text?:string;testimonial_display_text?:string;testimonial_approved:boolean;delivery_status:string;customer?:{name?:string;email?:string};job?:{job_title?:string}};
export default function FeedbackPage(){
 const [items,setItems]=useState<Survey[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState('');
 async function load(){setLoading(true);const r=await fetch('/api/feedback-surveys');const j=await r.json();if(r.ok)setItems(j.surveys||[]);else setError(j.error||'Kunne ikke hente data');setLoading(false)}
 useEffect(()=>{load()},[]);
 const stats=useMemo(()=>{const done=items.filter(x=>x.completed_at);return{sent:items.filter(x=>x.sent_at).length,replies:done.length,average:done.length?(done.reduce((n,x)=>n+(x.question_1_rating||0),0)/done.length).toFixed(1):'–',approved:items.filter(x=>x.testimonial_approved).length}},[items]);
 async function approve(id:string,value:boolean){const r=await fetch('/api/testimonials',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({surveyId:id,approved:value})});if(r.ok)setItems(v=>v.map(x=>x.id===id?{...x,testimonial_approved:value}:x))}
 return <div className="max-w-6xl space-y-6"><header><h1 className="text-2xl font-bold text-slate-900">Kundetilbakemeldinger</h1><p className="mt-1 text-sm text-slate-600">Forespørsler, svar og attester fra faktiske kundedata.</p></header>
 <section className="grid gap-4 sm:grid-cols-4">{[['Sendt',stats.sent],['Besvart',stats.replies],['Snitt av 10',stats.average],['Publisert',stats.approved]].map(([l,v])=><div key={l} className="rounded-xl border bg-white p-4"><p className="text-xs font-semibold uppercase text-slate-500">{l}</p><p className="mt-1 text-3xl font-bold">{v}</p></div>)}</section>
 {loading?<div className="flex items-center gap-2 text-slate-600"><Loader2 className="h-4 w-4 animate-spin"/>Henter data</div>:error?<div className="rounded-xl border border-red-200 bg-red-50 p-4 text-red-800">{error}</div>:items.length===0?<div className="rounded-xl border bg-white p-8"><h2 className="font-semibold">Ingen forespørsler ennå</h2><p className="mt-2 text-sm text-slate-600">Når en jobb markeres som fullført og automasjonen er aktivert, opprettes forespørselen her.</p></div>:<div className="space-y-3">{items.map(x=><article key={x.id} className="rounded-xl border bg-white p-5"><div className="flex flex-wrap items-start justify-between gap-4"><div><div className="flex items-center gap-2">{x.completed_at?<CheckCircle className="h-4 w-4 text-emerald-600"/>:<Clock className="h-4 w-4 text-amber-600"/>}<h2 className="font-semibold">{x.customer?.name||'Ukjent kunde'}</h2></div><p className="mt-1 text-sm text-slate-500">{x.job?.job_title||'Leveranse'} · {x.delivery_status}</p>{x.question_1_rating&&<p className="mt-3 font-semibold text-blue-700">{x.question_1_rating}/10</p>}{x.question_2_text&&<blockquote className="mt-2 rounded-lg bg-slate-50 p-3 text-sm text-slate-700">{x.question_2_text}</blockquote>}{x.question_3_text&&<p className="mt-2 text-sm text-slate-600"><strong>Forbedring:</strong> {x.question_3_text}</p>}</div>{x.testimonial_display_text&&<button onClick={()=>approve(x.id,!x.testimonial_approved)} className={`rounded-lg px-3 py-2 text-sm font-semibold ${x.testimonial_approved?'bg-emerald-100 text-emerald-800':'bg-blue-700 text-white'}`}>{x.testimonial_approved?'Publisert':'Godkjenn attest'}</button>}</div></article>)}</div>}
 <aside className="rounded-xl border border-blue-200 bg-blue-50 p-4 text-sm text-blue-900"><strong>Nettsidewidget:</strong> Godkjente attester kan vises med <code className="rounded bg-white px-1">/reviews/widget/DIN_BEDRIFTS_ID</code>. SMS forblir deaktivert til en SMS-leverandør og samtykke er konfigurert.</aside></div>;
}
